# Generated by Hybrid Cloud Works Migration Explorer 0.1.0
# Generated: 2026-10-03T12:00:00.000Z · input 9f4e78ae6374 · rules 1.0.35
# STATUS: ILLUSTRATIVE — NOT PRODUCTION-APPROVED. Run fmt/validate/tfsec or trivy/plan and obtain human approval.

module "data_services" {
  source              = "./modules/data_services"
  location            = var.location
  resource_group_name = var.resource_group_name
  tags                = var.tags
}

module "identity" {
  source              = "./modules/identity"
  location            = var.location
  resource_group_name = var.resource_group_name
  tags                = var.tags
}

module "monitoring" {
  source              = "./modules/monitoring"
  location            = var.location
  resource_group_name = var.resource_group_name
  tags                = var.tags
}

module "network" {
  source              = "./modules/network"
  location            = var.location
  resource_group_name = var.resource_group_name
  tags                = var.tags
}

module "shared_services" {
  source              = "./modules/shared_services"
  location            = var.location
  resource_group_name = var.resource_group_name
  tags                = var.tags
}

module "workload" {
  source              = "./modules/workload"
  location            = var.location
  resource_group_name = var.resource_group_name
  tags                = var.tags
}
